root: true
env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:jest/recommended'
  - 'prettier'
ignorePatterns:
  - 'vite.config.ts'
overrides:
  - files:
    - '**/__tests__/**/*.+(ts|tsx|js)'
    - '**/?(*.)+(spec|test).+(ts|tsx|js)'
    - '*.stories.@(ts|tsx|js)'
    extends:
      - 'plugin:jest/recommended'
      - 'plugin:jest-dom/recommended'
      - 'plugin:testing-library/react'
      - 'plugin:storybook/recommended'
    rules:
      import/no-default-export: off
      import/no-extraneous-dependencies: off
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 'latest'
  project: 'tsconfig.eslint.json'
  tsconfigRootDir: __dirname
  sourceType: 'module'
plugins:
  - '@typescript-eslint'
  - '@typescript-eslint/eslint-plugin'
  - 'eslint-plugin-react'
  - 'eslint-plugin-import'
  - 'eslint-plugin-jsx-ally'
  - 'eslint-plugin-react-hooks'
  - 'prefer-arrow'
  - 'react'
  - 'react-hooks'
  - 'jest'
  - 'jest-dom'
  - 'testing-library'
rules:
  react/react-in-jsx-scope: off