root: true
env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jest/recommended
  - prettier
  - prettier/@typescript-eslint
overrides:
  - files:
    - '**/__tests__/**/*.+(ts|tsx|js)'
    - '**/?(*.)+(spec|test).+(ts|tsx|js)'
    - '*.stories.@(ts|tsx|js)'
    extends:
      - plugin:jest-dom/recommended
      - plugin:testing-library/react
      - plugin:storybook/recommended
    rules:
      import/no-default-export: off
      import/no-extraneous-dependencies: off
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  project: ./tsconfig.eslint.json
  sourceType: module
  tsconfigRootDir: __dirname
plugins:
  - "@typescript-eslint"
  - "@typescript-eslint/eslint-plugin"
  - eslint-plugin-react
  - eslint-plugin-import
  - eslint-plugin-jsx-ally
  - eslint-plugin-react-hooks
  - prefer-arrow
  - react
  - react-hooks
  - jest
rules:
  react/react-in-jsx-scope: off
  prefer-arrow/prefer-arrow-functions:
    error:
      - disallowPrototype: true
      - singleReturnOnly: false
      - classPropertiesAllowed: false
      - namedComponents: arrow-function
      - unnamedComponents: arrow-function
